### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by mathieu-aubin** [cloudlinux/kernelcare-doc#15]
As i have no idea how to contact anyone... i'm opening this here.

the installer file located at https://kernelcare.com/installer doesn't isn't constant when searching for either apt-get or yum as package manager.

I'm running redhat related distros but i DO also have DPKG installed....

Line 26 does a `hash apt-get` which fails, that is expected.

then for some reason, another check is done on line 93 but this time using `hash dpkg`, which PASSES since it's installed... only the next command is `apt-get`, which fails and prohibits installation on develop systems like the ones i usually run.

I believe there would be better ways to install and check for package managers....

i guess i wont try that kernelcare thing

[![asciicast](https://asciinema.org/a/0xeoLvKDwTM7clEoMKGBxPUMp.svg)](https://asciinema.org/a/0xeoLvKDwTM7clEoMKGBxPUMp)

**Comment by histrio** [comment]
Hello Mathieu,
It was fixed recently. Could you please check it again?
Thanks for your feedback!

**Comment by histrio** [comment]
Hello @mathieu-aubin ! 
Can you confirm that the problem is disappeared?

**Comment by mathieu-aubin** [comment]
@histrio sorry i didnt see the initial message, thanks for the bump.

I would think that it works from the source code but you must take into account that `yum` is fading out and might not be around (even as a legacy symlink/alias, who knows) for long.

I would suggest you add `dnf` for Red Hat-related distros. CentOS 8 has switched to using `dnf` and Fedora has been staging it for quite a while now. There are also other distributions that use `dnf`.

Also, maybe.... and just maybe.... why not install directly using 'pure/legacy' package managers? It would create alot less isssues for you since `dpkg` and `rpm` mostly cover 90% of what is out there and even if `rpm` has some different versions from distros to distros, i'm pretty sure typical, basic commands are compatible from distros to distros. I might be wrong tho.

Anyways, check for least used first and maybe have a safety net in terms of accuracy in getting the environment more accurately.

Feel free to close this if you feel like it needs to. Take care

**Comment by mathieu-aubin** [comment]
actually, i still get an issue with apt/dpkg getting used by default even on a Fedora system (which should be .. yum/dnf/rpm

Theses release files are likely present on systems running matching names. Just in case it helps.
```
/etc/redhat-release
/etc/fedora-release
/etc/centos-release
```

here is my Fedora 32 /etc/fedora-release (redhat-release symlinks to it)
```
Fedora release 32 (Thirty Two)
```

then the /etc/os-release (or /usr/lib/os-release)
```
NAME=Fedora
VERSION="32 (Thirty Two)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Thirty Two)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```

**Comment by mathieu-aubin** [comment]
Good luck on this... it's a very simple script and i'm sure you can inspire yourself from many many many others out there doing the same with success. I mght have just replied ith too much informations aand i could have used that time to get you a working script instead! Bad time management. grr.
